"""
PDF Report Generator using ReportLab
"""
import os
import logging
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
from sqlalchemy import select

from app.core.config import settings

logger = logging.getLogger(__name__)

DARK_BG = colors.HexColor("#0f172a")
ACCENT = colors.HexColor("#06b6d4")
DANGER = colors.HexColor("#ef4444")
WARNING = colors.HexColor("#f59e0b")
SUCCESS = colors.HexColor("#22c55e")
MEDIUM_COLOR = colors.HexColor("#f97316")
INFO_COLOR = colors.HexColor("#3b82f6")
TEXT_DARK = colors.HexColor("#1e293b")
TEXT_MUTED = colors.HexColor("#64748b")
CARD_BG = colors.HexColor("#f8fafc")

SEVERITY_COLORS = {
    "CRITICAL": DANGER,
    "HIGH": colors.HexColor("#dc2626"),
    "MEDIUM": MEDIUM_COLOR,
    "LOW": WARNING,
    "INFO": INFO_COLOR,
}


class PDFGenerator:
    def __init__(self):
        os.makedirs(settings.REPORTS_DIR, exist_ok=True)

    async def generate(self, report_id: str) -> str:
        engine = create_async_engine(settings.DATABASE_URL)
        AsyncSession = async_sessionmaker(engine, expire_on_commit=False)

        try:
            async with AsyncSession() as db:
                from app.models.models import Report, Scan, Target, ScanFinding
                result = await db.execute(select(Report).where(Report.id == report_id))
                report = result.scalar_one_or_none()
                if not report:
                    raise ValueError(f"Report {report_id} not found")

                scan_result = await db.execute(select(Scan).where(Scan.id == report.scan_id))
                scan = scan_result.scalar_one_or_none()

                target_result = await db.execute(select(Target).where(Target.id == scan.target_id))
                target = target_result.scalar_one_or_none()

                findings_result = await db.execute(
                    select(ScanFinding).where(ScanFinding.scan_id == scan.id)
                )
                findings = findings_result.scalars().all()

                pdf_path = os.path.join(settings.REPORTS_DIR, f"report_{report_id}.pdf")
                self._build_pdf(pdf_path, report, scan, target, findings)

                report.pdf_path = pdf_path
                await db.commit()

                return pdf_path
        finally:
            await engine.dispose()

    def _build_pdf(self, path: str, report, scan, target, findings):
        doc = SimpleDocTemplate(
            path, pagesize=A4,
            rightMargin=2*cm, leftMargin=2*cm,
            topMargin=2*cm, bottomMargin=2*cm,
        )
        styles = self._get_styles()
        story = []

        # Header
        story.extend(self._build_header(report, target, styles))
        story.append(PageBreak())

        # Executive Summary
        story.extend(self._build_executive_summary(report, styles))

        # Risk Scorecard
        story.extend(self._build_risk_scorecard(report, styles))

        # Findings Table
        story.extend(self._build_findings_table(findings, styles))

        # Recommendations
        story.extend(self._build_recommendations(report, styles))

        # Footer info
        story.append(Spacer(1, 0.5*inch))
        story.append(HRFlowable(width="100%", thickness=1, color=TEXT_MUTED))
        story.append(Spacer(1, 0.1*inch))
        story.append(Paragraph(
            f"Generated by CyberGuard on {datetime.utcnow().strftime('%B %d, %Y')} | Confidential",
            styles["footer"]
        ))

        doc.build(story)

    def _get_styles(self):
        styles = getSampleStyleSheet()
        custom = {
            "title": ParagraphStyle("title", fontSize=28, textColor=DARK_BG, fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=6),
            "subtitle": ParagraphStyle("subtitle", fontSize=14, textColor=TEXT_MUTED, fontName="Helvetica", alignment=TA_CENTER, spaceAfter=20),
            "h2": ParagraphStyle("h2", fontSize=16, textColor=DARK_BG, fontName="Helvetica-Bold", spaceBefore=16, spaceAfter=8, borderPad=(0,0,4,0)),
            "h3": ParagraphStyle("h3", fontSize=12, textColor=DARK_BG, fontName="Helvetica-Bold", spaceBefore=8, spaceAfter=4),
            "body": ParagraphStyle("body", fontSize=10, textColor=TEXT_DARK, fontName="Helvetica", leading=16, alignment=TA_JUSTIFY, spaceAfter=8),
            "label": ParagraphStyle("label", fontSize=9, textColor=TEXT_MUTED, fontName="Helvetica", spaceAfter=2),
            "footer": ParagraphStyle("footer", fontSize=8, textColor=TEXT_MUTED, fontName="Helvetica", alignment=TA_CENTER),
            "badge": ParagraphStyle("badge", fontSize=9, textColor=colors.white, fontName="Helvetica-Bold", alignment=TA_CENTER),
            "finding_title": ParagraphStyle("finding_title", fontSize=10, textColor=TEXT_DARK, fontName="Helvetica-Bold"),
            "finding_desc": ParagraphStyle("finding_desc", fontSize=9, textColor=TEXT_DARK, fontName="Helvetica", leading=14),
        }
        return custom

    def _build_header(self, report, target, styles):
        elements = []
        elements.append(Spacer(1, 0.5*inch))

        # Title block
        elements.append(Paragraph("🛡️ CyberGuard", styles["subtitle"]))
        elements.append(Paragraph("Security Assessment Report", styles["title"]))
        elements.append(Spacer(1, 0.2*inch))

        # Target info table
        target_name = target.name if target else "Unknown"
        target_domain = target.domain if target else "N/A"
        target_ip = target.ip_address if target else "N/A"
        scan_date = report.created_at.strftime("%B %d, %Y") if report.created_at else "N/A"

        info_data = [
            ["Target", target_name, "Domain", target_domain],
            ["IP Address", target_ip or "N/A", "Scan Date", scan_date],
            ["Report ID", report.id[:16] + "...", "Risk Score", f"{report.risk_score:.1f}/100"],
        ]
        info_table = Table(info_data, colWidths=[1.5*inch, 2.5*inch, 1.5*inch, 2.5*inch])
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), CARD_BG),
            ("BACKGROUND", (2, 0), (2, -1), CARD_BG),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), TEXT_MUTED),
            ("TEXTCOLOR", (2, 0), (2, -1), TEXT_MUTED),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(info_table)
        elements.append(Spacer(1, 0.3*inch))

        # Risk score visual
        risk = report.risk_score
        risk_color = DANGER if risk >= 75 else WARNING if risk >= 50 else MEDIUM_COLOR if risk >= 25 else SUCCESS
        risk_label = "CRITICAL" if risk >= 75 else "HIGH" if risk >= 50 else "MEDIUM" if risk >= 25 else "LOW"

        risk_data = [[f"Overall Risk: {risk_label}", f"{risk:.1f} / 100"]]
        risk_table = Table(risk_data, colWidths=[5*inch, 2.5*inch])
        risk_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), risk_color),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (0, 0), 14),
            ("FONTSIZE", (1, 0), (1, 0), 20),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
            ("PADDING", (0, 0), (-1, -1), 14),
            ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ]))
        elements.append(risk_table)
        return elements

    def _build_executive_summary(self, report, styles):
        elements = [Spacer(1, 0.3*inch)]
        elements.append(Paragraph("Executive Summary", styles["h2"]))
        elements.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
        elements.append(Spacer(1, 0.1*inch))
        elements.append(Paragraph(report.executive_summary, styles["body"]))
        return elements

    def _build_risk_scorecard(self, report, styles):
        elements = [Spacer(1, 0.2*inch)]
        elements.append(Paragraph("Vulnerability Summary", styles["h2"]))
        elements.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
        elements.append(Spacer(1, 0.1*inch))

        counts = [
            ("CRITICAL", report.critical_count, DANGER),
            ("HIGH", report.high_count, colors.HexColor("#dc2626")),
            ("MEDIUM", report.medium_count, MEDIUM_COLOR),
            ("LOW", report.low_count, WARNING),
            ("INFO", report.info_count, INFO_COLOR),
        ]

        data = [["Severity", "Count", "Description"]]
        descriptions = {
            "CRITICAL": "Immediate action required — active exploitation risk",
            "HIGH": "Urgent remediation needed — significant security risk",
            "MEDIUM": "Should be addressed in near-term — moderate risk",
            "LOW": "Minor issues to address in regular maintenance",
            "INFO": "Informational findings — no immediate action required",
        }
        for sev, count, color in counts:
            data.append([sev, str(count), descriptions[sev]])

        table = Table(data, colWidths=[1.5*inch, 1*inch, 5*inch])
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), DARK_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 8),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ]
        for i, (sev, count, color) in enumerate(counts, 1):
            style.append(("TEXTCOLOR", (0, i), (0, i), color))
            style.append(("FONTNAME", (0, i), (0, i), "Helvetica-Bold"))
            if count > 0:
                style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#fff7ed") if sev in ["CRITICAL","HIGH"] else colors.HexColor("#f8fafc")))

        table.setStyle(TableStyle(style))
        elements.append(table)
        return elements

    def _build_findings_table(self, findings, styles):
        elements = [Spacer(1, 0.2*inch), PageBreak()]
        elements.append(Paragraph("Detailed Findings", styles["h2"]))
        elements.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
        elements.append(Spacer(1, 0.1*inch))

        severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        sorted_findings = sorted(
            findings,
            key=lambda f: severity_order.index(f.severity.value if hasattr(f.severity, 'value') else f.severity)
        )

        for finding in sorted_findings:
            sev = finding.severity.value if hasattr(finding.severity, 'value') else finding.severity
            color = SEVERITY_COLORS.get(sev, INFO_COLOR)

            sev_badge = Table([[sev]], colWidths=[1.2*inch])
            sev_badge.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), color),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("PADDING", (0, 0), (-1, -1), 4),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ]))

            title_para = Paragraph(finding.title, styles["finding_title"])
            cat_para = Paragraph(f"Category: {finding.category.replace('_', ' ').title()}", styles["label"])
            desc_para = Paragraph(finding.description, styles["finding_desc"])

            row_data = [[sev_badge, [title_para, cat_para, desc_para]]]
            if finding.remediation:
                rem_para = Paragraph(f"Remediation: {finding.remediation}", styles["finding_desc"])
                row_data = [[sev_badge, [title_para, cat_para, desc_para, rem_para]]]

            row_table = Table(row_data, colWidths=[1.4*inch, 6.1*inch])
            row_table.setStyle(TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
            ]))
            elements.append(row_table)
            elements.append(Spacer(1, 0.08*inch))

        return elements

    def _build_recommendations(self, report, styles):
        elements = [Spacer(1, 0.2*inch)]
        elements.append(Paragraph("Recommendations", styles["h2"]))
        elements.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
        elements.append(Spacer(1, 0.1*inch))

        recs = report.recommendations or {}
        sections = [
            ("Immediate Actions", recs.get("immediate", []), DANGER),
            ("Short-Term Actions (1-4 weeks)", recs.get("short_term", []), WARNING),
            ("Long-Term Actions (1-3 months)", recs.get("long_term", []), INFO_COLOR),
        ]

        for title, items, color in sections:
            if not items:
                continue
            elements.append(Paragraph(title, styles["h3"]))
            for item in items:
                elements.append(Paragraph(f"• {item}", styles["body"]))
            elements.append(Spacer(1, 0.1*inch))

        return elements
